name: Deploy Backend Flask Server to Render

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    paths-ignore:
      - README.md
      - client/** # Should only run on backend changes
      - .gitignore
      - .github/**
  workflow_dispatch:

jobs:
  test-job:
    uses: cyanChill/GitInspire/.github/workflows/text_backend.yml
  
  deploy-job-success:
    if: success()
    needs: [test-job]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Notify user that workflow tests passed
        run: echo 'The triggering workflow passed'
      - name: Deploy our app to Render
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}

  deploy-job-fail:
    if: failure()
    needs: [test-job]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Notify user that workflow tests failed
        run: echo 'The triggering workflow failed'
      - name: Cause action to fail
        run: exit 1
