name: Test & Deploy Client

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - backend/** # Should only run on client changes
      - .gitignore
      - .github/**
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_CLIENT_ID: "test"
      NEXT_PUBLIC_REDIRECT_URI: "http://localhost:3000/auth/login"
      NEXT_PUBLIC_GITHUB_AUTH_URL: "https://github.com/login/oauth/authorize?client_id=test&redirect_uri=http://localhost:3000/auth/login"
      NEXT_PUBLIC_DOMAIN: "https://gitinspire.vercel.app"
      NEXT_PUBLIC_BACKEND_URL: "http://localhost:5000"
    defaults:
      run:
        working-directory: ./client
    strategy:
      matrix:
        node-version: [16, 18, 19]
    name: Node.js ${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci and test
        run: |
          npm ci
          npm test

  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v3
      - uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: PR
      - name: Exit if not push to main
        if: needs.pr-check.outputs.number != 'null'
        run:  |
          gh run cancel ${{ github.run_id }}
          gh run watch ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy our app to Vercel if success [for push on main]
        if: ${{ success() }}
        run: curl ${{ secrets.VERCEL_DEPLOY_HOOK }}
      - name: Cause action to fail if tests failed
        if: ${{ failure() }}
        run: exit 1
